/*
 * Emits `dist/tokens.css` — the token layers only, no component CSS.
 *
 * Why this exists: the library build (vite.config.ts) sets `cssCodeSplit: false`
 * so every stylesheet collapses into one `dist/design-system.css`. That is right
 * for a consumer using the components, but an app adopting *tokens only* (rung
 * L1 in docs/consumers.md) would drag in every `.ds-*` rule it never renders.
 *
 * Vite has no second CSS-only lib entry, so we flatten the `@import` chain in
 * `src/tokens/index.css` ourselves. The chain is deliberately one level deep and
 * uses no `url()` references, which makes plain concatenation in import order
 * exactly equivalent to what a bundler would produce.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const entry = resolve(root, 'src/tokens/index.css');
const out = resolve(root, 'dist/tokens.css');

const IMPORT = /^@import\s+'([^']+)';$/;

/** Concatenate an entry's `@import`s in order, keeping every other line as-is. */
async function flatten(file) {
  const source = await readFile(file, 'utf8');
  const parts = [];

  for (const line of source.split('\n')) {
    const match = IMPORT.exec(line.trim());
    if (!match) {
      parts.push(line);
      continue;
    }

    const imported = resolve(dirname(file), match[1]);
    if (imported.includes('/components/')) {
      throw new Error(`${file} imports component CSS (${match[1]}) — tokens.css must stay token-only`);
    }
    parts.push(await flatten(imported));
  }

  return parts.join('\n');
}

const banner = [
  '/*',
  ' * @jemmy8oy-northstar/design-system — tokens only (primitives → semantic roles → themes → base).',
  ' *',
  ' * Generated by scripts/build-tokens.mjs. Do not edit; edit src/tokens/* instead.',
  ' * This is the L1 adoption artefact: vendor this one file to inherit the design',
  ' * language without taking the components. See docs/consumers.md.',
  ' */',
  '',
].join('\n');

await mkdir(dirname(out), { recursive: true });
await writeFile(out, banner + (await flatten(entry)) + '\n', 'utf8');
console.log(`build-tokens: wrote ${out}`);
